const POLICY_CLASS = {
  CRITICAL_OPERATIONAL: "CRITICAL_OPERATIONAL",
  WARNING_OPERATIONAL: "WARNING_OPERATIONAL",
  QUALITY: "QUALITY",
  HISTORICAL: "HISTORICAL",
};

const CONFIDENCE = {
  HIGH: "HIGH",
  MEDIUM: "MEDIUM",
  LOW: "LOW",
};

module.exports = { POLICY_CLASS, CONFIDENCE };
